### Create new User
POST http://localhost:3001/auth/create
Content-Type: application/json

{
   "name": "Khoa",
   "username": "nak",
   "email": "khoa@gmail.com"
}

### Check email and username

POST http://localhost:3001/auth/check-user
Content-Type: application/json

{
   "name": "Khoa",
   "username": "nak",
   "email": "khoa@gmail.com"
}

### User Login

POST http://localhost:3001/auth/login
Content-Type: application/json

{
   "usernameOrEmail": "khoa@gmail.com",
   "password": "asdasd"
}

### Get User by Id

GET http://localhost:3001/users/6198ffbf00063d193db04b88

### Change theme

PUT http://localhost:3001/users/change-theme/619bb0920ccecdb2f27cb7cf/21"

### Update todoListRouter
PUT http://localhost:3001/users/update-todo-list/619c4b2beee42bd7dd7cc710/619bd72733092f9e8edc6d1b


### Get all Task
POST http://localhost:3001/todo-list
Content-Type: application/json

{
   "taskList": ["619bd479a1b372e76710604d", "619bd479a1b372e76710604d", "619bd72733092f9e8edc6d1b", "619c55c626646f5e61526bb6", "619c573f26646f5e61526bbc", "619c576626646f5e61526bc0", "619c579e26646f5e61526bc4"]
}


### Add task
POST http://localhost:3001/todo-list/add-task
Content-Type: application/json

{
   "title": "Learning Sports"
}

### DeleteTask
DELETE http://localhost:3001/todo-list/delete-task/619bcf955ad89278d11bdd95

### Edit Task
POST http://localhost:3001/todo-list/edit-task/619bd473a1b372e76710604b
Content-Type: application/json

{
   "title": "Learning Nothing"
}